"use client";

// import "./globals.css";
import { ThemeProvider } from "next-themes";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <link href="../../assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
      <link href="../../assets/css/icons.min.css" rel="stylesheet" type="text/css" />
      <link href="../../assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />

      <script src="../../assets/libs/jquery/jquery.min.js"></script>
      <script src="../../assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="../../assets/libs/metismenu/metisMenu.min.js"></script>
      <script src="../../assets/libs/simplebar/simplebar.min.js"></script>
      <script src="../../assets/libs/node-waves/waves.min.js"></script>
      <script src="../../assets/libs/waypoints/lib/jquery.waypoints.min.js"></script>
      <script src="../../assets/libs/jquery.counterup/jquery.counterup.min.js"></script>
     
      <link
        href="../../assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css"
        rel="stylesheet"
        type="text/css"
      />
      <link
        href="../../assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css"
        rel="stylesheet"
        type="text/css"
      />

      <link
        href="../../assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css"
        rel="stylesheet"
        type="text/css"
      />

      <link
        href="../../assets/css/bootstrap.min.css"
        id="bootstrap-style"
        rel="stylesheet"
        type="text/css"
      />
      <link
        href="../../assets/css/icons.min.css"
        rel="stylesheet"
        type="text/css"
      />
      <link
        href="../../assets/css/app.min.css"
        id="app-style"
        rel="stylesheet"
        type="text/css"
      />

      <script src="../../assets/libs/jquery/jquery.min.js"></script>
      <script src="../../assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="../../assets/libs/metismenu/metisMenu.min.js"></script>
      <script src="../../assets/libs/simplebar/simplebar.min.js"></script>
      <script src="../../assets/libs/node-waves/waves.min.js"></script>
      <script src="../../assets/libs/waypoints/lib/jquery.waypoints.min.js"></script>
      <script src="../../assets/libs/jquery.counterup/jquery.counterup.min.js"></script>


      <script src="../../assets/js/app.js"></script>
      <body className={inter.className} data-layout="horizontal"
          data-topbar="colored">
        {/* <ThemeProvider attribute="class" defaultTheme="dark" enableSystem> */}
          <Header />
          {children}
        {/* </ThemeProvider> */}
        <script src="../assets/libs/jquery/jquery.min.js"></script>
        <script src="../assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="../assets/libs/metismenu/metisMenu.min.js"></script>
        <script src="../assets/libs/simplebar/simplebar.min.js"></script>
        <script src="../assets/libs/node-waves/waves.min.js"></script>
        <script src="../assets/libs/waypoints/lib/jquery.waypoints.min.js"></script>
        <script src="../assets/libs/jquery.counterup/jquery.counterup.min.js"></script>

    
        <script src="../assets/js/pages/materialdesign.init.js"></script>

        <script src="../assets/js/app.js"></script>


      </body>
    </html>
  );
}
